# Details of the overall pipeline
pipeline:
  # Location(s) where the code for the building images is kept.
  # Needed because we need to examine the stages in the pipeline
  images: [./images]
  stages:   [tomography, pz_stack, treecorr]
  # Working directory:
  owner:    joezuntz
  basename: desc-pipe
  version:  1.0
  #Overall inputs to the whole pipeline.
  #Keys are as used by the modules.


# details of where the pipeline is to be run and where to get local inputs
runtime:
  launcher: local
  working:   ./work
  #Place to read configuration files for each stage
  config:   ./test/config
  #Place to copy the outputs to:
  output:   ./test/output
  # Pipeline details (determines the Docker image name)
  inputs:
    shear-catalog: ./test/inputs/des-sv-ngmix-pipetest.fits
    photoz-catalog: ./test/inputs/des-sv-annz-pipetest.fits


# Stages in the pipeline

# Put the objects into bins.
tomography:
  depends-on: []
  config:
    config: tomo-config.yaml

pz_stack:
  depends-on: [tomography]
  config: {}

treecorr:
  depends-on: [tomography, pz_stack]
  config:
    config: treecorr-config.yaml  
  # something like this?
  nodes: 1
  processes: 1
  minutes: 5

